# **Study Project:** *Transformer model for prediction of grasping movements*

## Import packages

In [1]:
!pip install ultralytics
!pip install pydrive
!pip install -U -q PyDrive

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 645.2/645.2 kB 7.9 MB/s eta 0:00:00


In [2]:
import os
import cv2
import numpy as np
import IPython.display as ipd

from scipy import interpolate
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
#!pip install ultralytics
#ipd.clear_output()
import ultralytics

In [3]:
#Debugging
import sys

## Helper functions

In [4]:
def GetBoundingBoxes(videopath):
    """
    Extract bounding boxes from video.

    Args:
    videopath -- path to video to extract bounding boxes from.
    """
    # Use object tracker to get the bounding boxes and classIDs in a 'results' object
    bbs = np.zeros((1, 7))
    # It is also possible to pass the whole folder as path,
    # but we still want the flexibility to access single videos
    results = model.track(source=videopath, tracker="bytetrack.yaml")

    # Get class names
    classes = results[0].names

    # Iterate through each frame of a video to get all bounding boxes for a frame
    for frame in range(len(results)):

        # x_center, y_center, bbwidth, bbheight of bbs of this frame
        xywh = results[frame].boxes.xywh.detach().cpu().numpy()
        n = len(xywh) # number of bounding boxes
        cls = results[frame].boxes.cls.detach().cpu().numpy().reshape((n,1))
        # if the object tracker is currently tracking at least one object, save the trackingID for that object, else fill with -1 placeholder
        trackingID = results[frame].boxes.id.detach().cpu().numpy().reshape((n,1)) if results[frame].boxes.is_track else np.repeat(-1, n).reshape((n,1))
        frame_count = np.repeat(frame, n).reshape((n,1))

        # bind the data together for one frame
        data = np.concatenate((frame_count, cls, xywh, trackingID), axis=1)
        # add all data of this frame to all data of this video
        bbs = np.concatenate((bbs, data), axis=0)

    return bbs, classes

In [15]:
def Center(videopath, to_path, bounding_boxes, width=1920, height=1120):

    """
    Create a video where a target object is always centered.

    Args:
    videopath -- path to video to center
    to_path -- location to export centered video to
    bounding_boxes -- bbs of object to center on
    width -- output video dim x, default=1920
    height -- output video dim y, default=1120
    """

    # 1. Read video
    cap = cv2.VideoCapture(videopath)
    frameCount = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    frameWidth = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    frameHeight = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    FPS = int(cap.get(cv2.CAP_PROP_FPS))

    video = np.zeros((frameCount, frameHeight, frameWidth, 3), np.dtype('uint8'))
    fc = 0
    ret = True

    while (fc < frameCount and ret):
        ret, video[fc] = cap.read()
        fc += 1

    cap.release()


    # 2. Correct video
    bbs = bounding_boxes
    width = width
    height = height
    center_x = (width/2)
    center_y = (height/2)
    x_dists = []
    y_dists = []

    for box_pos in bbs:
        if np.isnan(box_pos).any():
            # if all values were nan, then 0 would be the max, so the corrected video would be the original video
            x_dists.append(0)
            y_dists.append(0)
        else:
            # get center of bb
            #center_x_bb = (box_pos[0] + box_pos[2]) / 2
            #center_y_bb = (box_pos[1] + box_pos[3]) / 2
            center_x_bb = box_pos[0]
            center_y_bb = box_pos[1]
            # calculate distances
            x_dists.append(abs(center_x-center_x_bb))
            y_dists.append(abs(center_y-center_y_bb))


    video_corrected = np.zeros((len(video),
                              int(height + max(y_dists)*2),
                              int(width + max(x_dists)*2),
                              3), dtype=int)

    # 3. Center video
    # get coords for placement height and width. may be switched
    start_row = (video_corrected.shape[1] - height) // 2
    start_col = (video_corrected.shape[2] - width) // 2

    offsets = np.zeros(shape=(len(video),2))

    for idx, frame in enumerate(video):

        # get matching bb
        box_curr = bbs[idx]

        # If there is no information on fruit, color the frame black (skip iter)
        if np.isnan(box_curr).any():
            continue
            # frame[:] = 0
            # frame = np.zeros(frame.shape)
        else:
            # get center of bb
            #center_x_bb = (box_curr[0] + box_curr[2]) / 2
            #center_y_bb = (box_curr[1] + box_curr[3]) / 2
            center_x_bb = box_curr[0]
            center_y_bb = box_curr[1]

            # get offset of center
            # pos if bounding box is to right of center, else negative
            x_offset = int(center_x_bb - center_x)
            # pos if bounding box is below center, else negative
            y_offset = int(center_y_bb - center_y)

            #!coordinates until here are for old video

            #get fitting indices for new video
            fixed_start_row = start_row - y_offset
            fixed_start_col = start_col - x_offset

            fixed_end_row = fixed_start_row + height
            fixed_end_col = fixed_start_col + width

            # Checkup
            if((fixed_start_row or
                fixed_start_col or
                fixed_end_row or
                fixed_end_col) < 0):
                print("Negative Index!")

            # Save centered + corrected in new video
            video_corrected[idx][fixed_start_row:fixed_end_row,
                              fixed_start_col:fixed_end_col] = frame

            #Save offsets
            offsets[idx,:] = x_offset, y_offset


    # 4. Save video
    video_corrected = np.uint8(video_corrected)

    height_new = int(video_corrected.shape[1])
    width_new = int(video_corrected.shape[2])

    fourcc = cv2.VideoWriter_fourcc(*"mp4v")
    out = cv2.VideoWriter(to_path[:-4]+'_centered.mp4', fourcc, FPS, (width_new, height_new), True)
    for idx in range(len(video)):
        out.write(video_corrected[idx])
    out.release()

    return offsets, (start_row, start_col)


## Video centering

In [16]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [17]:
#Acess google drive with pydrive to safe BBs and Offsets
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

# Set the destination Google Drive folder ID. Folder Name: Centering_OffsetsAndBBs under Data
offsets_folder_id = '1d6hcNnHVwsEexY2GDoHGCSLQZYZUbfcs'
bbs_targets_folder_id = '1yS_eBVOe-f5R-UIsyyZiWiG37t0s5od2'
bbs_hands_folder_id = '1mVdxyoVfBp6LU-KNgWwZ28NLDEn9KNf0'

In [18]:
# Load model
model = ultralytics.YOLO('yolov8n.pt')

# List videos
#folderpath = '/content/drive/MyDrive/Study_Project_Grasping_Copy/Transformer/Trials/'
#labelpath = '/content/drive/MyDrive/Study_Project_Grasping_Copy/Transformer/Labels/'
#folder = [f for f in os.listdir(folderpath) if os.path.isfile(os.path.join(folderpath, f))]
folderpath = '/content/drive/MyDrive/Study Project: Grasping/Transformer/Data/Trials2/'
labelpath = '/content/drive/MyDrive/Study Project: Grasping/Transformer/Data/Labels2/'
folder = [f for f in os.listdir(folderpath) if os.path.isfile(os.path.join(folderpath, f))]

# Example video
#ipd.Video(folderpath+'banana02.mp4', width=1920/1.7, height=1120/1.7)

**Procedure:**
1. Get the bounding boxes of all objects in each raw video.
2. Filter for hand and target object bounding boxes.
3. Target centering: fixate the target object (TARGET.mp4) using interpolation.

In [19]:
# Iterate through every video file in the folder
for i, video in enumerate(folder):

    print(f"Video {i+1}/{len(folder)}: {video}\n")

    # Get length of input array (number of frames)
    cap = cv2.VideoCapture(folderpath+video)
    frameCount = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    cap.release()


    # 1. Get all bbs of this video
    # (x_center, y_center, bbwidth, bbheight, class, trackerID, frame, filename)
    bbs, classes = GetBoundingBoxes(folderpath+video)
    video_count = np.repeat(i, len(bbs)).reshape((len(bbs),1))
    bbs = np.concatenate((video_count, bbs), axis=1)



    # 2. Filter for hand and target fruit by class
    # Get the target class to filter for as number
    if '.mov' in video:
        # returns the string name without '00.mp4' ending (could add try-catch)
        target_class = video[:-6]
    #added this, why was it .mov??
    elif '.mp4' in video:
        # returns the string name without '00.mp4' ending (could add try-catch)
        target_class = video[:-6]


    # Get class number from lookup table
    target_class = list(classes.keys())[list(classes.values()).index(target_class)]
    hand_class = list(classes.keys())[list(classes.values()).index('person')]

    # Filter data
    target_bbs = bbs[(bbs[:, 2] == target_class)]
    hand_bbs = bbs[(bbs[:, 2] == hand_class)]

    # To Do: Use trackerID to track the same object
    # -> could be added later on, as we only use one object per trial?
    # -> but if we have detection of more than one target fruit, it breaks something
    # because it will try to calculate positions from more than one bb per frame.
    # problem so far: if detection ends for one frame, a new trackerID is assigned
    # -> for this approach to work we would have to compare the position of the
    # last tracked trackerID to each object with newly assigned trackerID and
    # take the closest one, and interpolate position if there are no new trackerIDs detected.
    # for now, we leave it out: remove class and trackingID
    target_bbs = target_bbs[:, [0,1,3,4,5,6]]
    hand_bbs = hand_bbs[:, [0,1,3,4,5,6]]

    # 3. Interpolation: take last known bounding box positions
    # (x_center_fruit, y_center_fruit, bbwidth_fruit, bbheight_fruit, class, trackerID, frame, filename, x_center_hand, y_center_hand, bbwidth_hand, bbheight_hand)
    vid_input = np.zeros((frameCount, 10))
    vid_input[:] = np.nan # use as 'no information' instead of nan, because nan is a string


    #Perform interpolation for targets

    #get x values for which detection was successful
    x_detects = [int(target_bb[1]) for target_bb in target_bbs]
    #get x values for which interpolation has to be performed
    x_to_interp = [xframe for xframe in range(len(vid_input)) if xframe not in x_detects]

    #get the values for successful detections
    x_centers_targets_detec = np.asarray([frame_value[2] for frame_value in target_bbs])
    y_centers_targets_detec = np.asarray([frame_value[3] for frame_value in target_bbs])
    bbwidths_targets_detec = np.asarray([frame_value[4] for frame_value in target_bbs])
    bbheights_targets_detec = np.asarray([frame_value[5] for frame_value in target_bbs])

    #interpolate
    #numpy.interp(x, xp, fp, left=None, right=None, period=None)
    inter_x_centers_target = np.interp(x_to_interp, x_detects, x_centers_targets_detec)
    inter_y_centers_target = np.interp(x_to_interp, x_detects, y_centers_targets_detec)
    inter_bbwidths_target = np.interp(x_to_interp, x_detects, bbwidths_targets_detec)
    inter_bbheights_target = np.interp(x_to_interp, x_detects, bbheights_targets_detec)

    #Combine values into single array
    #add frame and video indices for new array
    #frame indices
    all_frames = [frame for frame in range(len(vid_input))]
    vid_input[all_frames,1] = range(len(vid_input))
    #video indices
    vid_input[all_frames,0] = i

    #pseudo: vid_input[all_detec_xs][einzeln 2 bis 4 für die werte (in versch zeilen)] =  x_centers_targets_detec bis bbheights_targets_detec in den zeilen
    vid_input[x_detects,2] = x_centers_targets_detec
    vid_input[x_detects,3] = y_centers_targets_detec
    vid_input[x_detects,4] = bbwidths_targets_detec
    vid_input[x_detects,5] = bbheights_targets_detec

    #und dasselbe für interpolated
    vid_input[x_to_interp,2] = inter_x_centers_target
    vid_input[x_to_interp,3] = inter_y_centers_target
    vid_input[x_to_interp,4] = inter_bbwidths_target
    vid_input[x_to_interp,5] = inter_bbheights_target


    #Perform interpolation for hands

    #get x values for which detection was successful
    x_detects = [int(hand_bb[1]) for hand_bb in hand_bbs]
    #get x values for which interpolation has to be performed
    x_to_interp = [xframe for xframe in range(len(vid_input)) if xframe not in x_detects]

    #get the values for successful detections
    x_centers_hand_detec = np.asarray([frame_value[2] for frame_value in hand_bbs])
    y_centers_hand_detec = np.asarray([frame_value[3] for frame_value in hand_bbs])
    bbwidths_hand_detec = np.asarray([frame_value[4] for frame_value in hand_bbs])
    bbheights_hand_detec = np.asarray([frame_value[5] for frame_value in hand_bbs])

    #interpolate
    #numpy.interp(x, xp, fp, left=None, right=None, period=None)
    inter_x_centers_hand = np.interp(x_to_interp, x_detects, x_centers_hand_detec)
    inter_y_centers_hand = np.interp(x_to_interp, x_detects, y_centers_hand_detec)
    inter_bbwidths_hand = np.interp(x_to_interp, x_detects, bbwidths_hand_detec)
    inter_bbheights_hand = np.interp(x_to_interp, x_detects, bbheights_hand_detec)

    #Combine values into single array
    #add frame and video indices for new array
    #frame indices
    all_frames = [frame for frame in range(len(vid_input))]
    vid_input[all_frames,1] = range(len(vid_input))
    #video indices
    vid_input[all_frames,0] = i

    #pseudo: vid_input[all_detec_xs][einzeln 2 bis 4 für die werte (in versch zeilen)] =  x_centers_targets_detec bis bbheights_targets_detec in den zeilen
    vid_input[x_detects,6] = x_centers_hand_detec
    vid_input[x_detects,7] = y_centers_hand_detec
    vid_input[x_detects,8] = bbwidths_hand_detec
    vid_input[x_detects,9] = bbheights_hand_detec

    #und dasselbe für interpolated
    vid_input[x_to_interp,6] = inter_x_centers_hand
    vid_input[x_to_interp,7] = inter_y_centers_hand
    vid_input[x_to_interp,8] = inter_bbwidths_hand
    vid_input[x_to_interp,9] = inter_bbheights_hand


    # get first frame with information of target (used for input later)
    start_frame = 0
    for i, frame in enumerate(vid_input[:, :6]):
        if np.isnan(frame).any():
            start_frame = i+1
        else:
            break


    # 4. Center: Center on the correct bounding boxes of the target fruit
    offsets, start_cords = Center(folderpath+video, labelpath+video, vid_input[:, 2:6])

    new_target_bbs = vid_input[:,2:6]#.copy()
    new_hand_bbs = vid_input[:,6:]#.copy()

    #Get offsets of target from center of OG video
    x_offsets = offsets[:,0]
    y_offsets = offsets[:,1]

    start_x = start_cords[1]
    start_y = start_cords[0]

    #Calculate Bounding boxes in bigger video before centering
    #Adjust x
    new_target_bbs[:,0] += start_x
    new_hand_bbs[:,0] += start_x

    #Adjust y
    new_target_bbs[:,1] += start_y
    new_hand_bbs[:,1] += start_y

    #Now adjust for after centering based on offsets
    #Adjust x
    new_target_bbs[:,0] -= x_offsets
    new_hand_bbs[:,0] -= x_offsets

    #Adjust y
    new_target_bbs[:,1] -= y_offsets
    new_hand_bbs[:,1] -= y_offsets


    targets_folderID = '1u6jLaX4Mb5UtQzDGtXvQPgwJIbG92YBT'
    hands_folderID = '1901iQUf4nCOi1ZPJRuyJeEQ0MweQKlka'

    #Create npz files
    np.savez('Post_Centering_BBs_Target_Video_{}.npz'.format(i), array=new_target_bbs)
    np.savez('Post_Centering_BBs_Hand_Video_{}.npz'.format(i), array=new_hand_bbs)

    #Write npz files to drive
    Post_Centering_BBs_Target = drive.CreateFile({'title': 'Post_Centering_BBs_Target_Video_{}.npz'.format(i), 'parents': [{'id': targets_folderID}]})
    Post_Centering_BBs_Target.SetContentFile('Post_Centering_BBs_Target_Video_{}.npz'.format(i))
    Post_Centering_BBs_Target.Upload()

    Post_Centering_BBs_Hands = drive.CreateFile({'title': 'Post_Centering_BBs_Hand_Video_{}.npz'.format(i), 'parents': [{'id': hands_folderID}]})
    Post_Centering_BBs_Hands.SetContentFile('Post_Centering_BBs_Hand_Video_{}.npz'.format(i))
    Post_Centering_BBs_Hands.Upload()


Video 1/1: banana02.mp4





WARNING ⚠️ inference results will accumulate in RAM unless `stream=True` is passed, causing potential out-of-memory
errors for large sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

video 1/1 (1/116) /content/drive/MyDrive/Study Project: Grasping/Transformer/Data/Trials2/banana02.mp4: 384x640 1 orange, 1 bed, 1 tv, 1 laptop, 1 keyboard, 1 cell phone, 11.3ms
video 1/1 (2/116) /content/drive/MyDrive/Study Project: Grasping/Transformer/Data/Trials2/banana02.mp4: 384x640 1 person, 1 orange, 1 bed, 1 tv, 1 laptop, 1 keyboard, 7.5ms
video 1/1 (3/116) /content/drive/MyDrive/Study Project: Grasping/Transformer/Data/Trials2/banana02.mp4: 3

In [20]:
#For Banana video:
    #New X Center For Trials2 Banana video should be 1245.589599609375
    #New Y Center For Trials2 Banana video should be 587.0914916992188
print(new_target_bbs)

[[     1245.9      587.91      225.45       167.3]
 [     1245.9      587.91      225.45       167.3]
 [     1245.9      587.91      225.45       167.3]
 [     1245.9      587.91      225.45       167.3]
 [     1245.9      587.91      225.45       167.3]
 [     1245.9      587.91      225.45       167.3]
 [     1245.9      587.91      225.45       167.3]
 [     1245.9      587.91      225.45       167.3]
 [     1245.9      587.91      225.45       167.3]
 [     1245.9      587.91      225.45       167.3]
 [     1245.9      587.91      225.45       167.3]
 [     1245.9      587.91      225.45       167.3]
 [     1245.9      587.91      225.45       167.3]
 [     1245.9      587.91      225.45       167.3]
 [     1245.9      587.91      225.45       167.3]
 [     1245.4      587.66      213.52       170.9]
 [     1245.3      587.64      213.42      171.04]
 [     1245.7      587.53      213.18      171.12]
 [     1245.1       587.9      217.46      170.94]
 [     1245.3      587.87      

In [21]:
#print(new_target_bbs)
#print("\n",vid_input[:, 2:6])
#print("\n",offsets)
if(new_target_bbs == vid_input[:,2:6]).all():
    print("error")

print(x_offsets)
#print(y_offsets)
"""
test_bbs_target = vid_input[:,2:6]
test_bbs_target_x = test_bbs_target[:,0]
test_bbs_target_x_new = test_bbs_target[:,0] + x_offsets
#print(test_bbs_target_new)
print("test_bbs_target_x:",test_bbs_target_x)
print("test_bbs_target_new:",test_bbs_target_x_new)
if(test_bbs_target_x == test_bbs_target_x_new).all():
    print("error")

#Adjust x
test_bbs_target[:,0] += x_offsets
print(test_bbs_target)
print("\n",new_target_bbs)
"""

error
[        284         284         284         284         284         284         284         284         284         284         284         284         284         284         284         269         269         269         268         268         265         265         265         265         266         268
         268         269         270         271         271         271         273         273         280         280         280         272         281         274         282         274         277         280         283         282         274         274         274         274         274         274
         273         273         275         277         279         281         283         285         284         284         284         281         277         273         273         270         268         265         263         260         258         255         253         250         248         248
         248         248         248         248       

'\ntest_bbs_target = vid_input[:,2:6]\ntest_bbs_target_x = test_bbs_target[:,0]\ntest_bbs_target_x_new = test_bbs_target[:,0] + x_offsets\n#print(test_bbs_target_new)\nprint("test_bbs_target_x:",test_bbs_target_x)\nprint("test_bbs_target_new:",test_bbs_target_x_new)\nif(test_bbs_target_x == test_bbs_target_x_new).all():\n    print("error")\n\n#Adjust x\ntest_bbs_target[:,0] += x_offsets\nprint(test_bbs_target)\nprint("\n",new_target_bbs)\n'